### ISSUE TITLE
if there are no values configured for captcha, then captcha should be disabled

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#427]
captcha should only be active or called IF its configured else, it should be disabled as people may not want to stand this up with captcha

**Comment by b-solution** [comment]
@bluenevus I've fixed these issue, please test it again and let me know if its not working.

**Comment by bluenevus** [comment]
example of what it looks like when I put the values where I still get a blank page

![image](https://user-images.githubusercontent.com/3675043/168321768-6a9de9fa-209c-480b-8852-c23c9a1898e8.png)

clicked the captcha

![image](https://user-images.githubusercontent.com/3675043/168321855-d14403b1-b442-469f-8543-a11cff6a6247.png)

in this case where values exist, nothing in js console but a blank page also 

![image](https://user-images.githubusercontent.com/3675043/168321996-a06c2e2b-8a79-4eb2-8a5a-4300c2eae3bb.png)

**Comment by b-solution** [comment]
@bluenevus  I've fixed this issue, please test it again and let me know if its not working.
