### ISSUE TITLE
Replace existing Flow Map with copy of Tree Chart, but make it function horizontally

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#429]
Replace Flow Chart with a **COPY** of Tree Chart, but make it function horizontally instead of vertically.
Screenshot Example

![flow_map_replace_with_horizontal_tree_chart](https://user-images.githubusercontent.com/11938477/162247499-a6ea9585-0a9a-4fd0-a941-21257a6b8f56.png)

**Comment by b-solution** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/162557805-8aa5ccce-1f7e-405c-a94f-cd9e9a21d4d8.png">

**Comment by bluenevus** [comment]
treechart and flow map doesn't behave correctly after this update.  
clicking + then entering dat duplicates what is being typed
![image](https://user-images.githubusercontent.com/3675043/162579092-03284c8c-829d-40d8-a72d-7751be8d2a14.png)

carriage return or lost of focus should save what is typed but it doesn't anymore on either chart

it starts in the lower left hand corner vs the middle like your picture
![image](https://user-images.githubusercontent.com/3675043/162579139-09d5f641-3c58-4420-b727-631535df3698.png)

this happend to both the treechart and flow map.  both just don't work.  can't add nodes as it get stuck because it won't save.  I tried to refresh and maybe the text of one node saved and the rest didn't and I can't save the other text

**Comment by bluenevus** [comment]
another example of the treechart now doing the same thing where it worked before
![image](https://user-images.githubusercontent.com/3675043/162580874-592cefb9-5b7f-4cee-9f74-80c4a706c0f6.png)

**Comment by b-solution** [comment]
@bluenevus I've fixed these issue please test it again and let me know if its not work.

**Comment by bluenevus** [comment]
doesn't work. I clobbered the assets, I did a bundle pristine and a gem pristine just to make sure it was all clean however, it still broken  @b-solution

**Comment by bluenevus** [comment]
so its not saving after a carriage return or loss of focus or when I click the plus to add another node.  THE ONLY way it saves is to refresh so for example in this chart I typed judy then click browser refresh then I could add a node and type bob then click refresh then I coudl add another node and jane and so forth.  It should have saved the map after a carriage return but that didn't work.  Also when I tried clicking away it wouldn't work.  I tried to click the + to add a node hoping it would save and it would not.  The only way it saves in order to add a node is to refresh the page

![image](https://user-images.githubusercontent.com/3675043/163196039-ea0cd5d5-b8e1-4bff-b150-0dead6b7a551.png)

**Comment by LAlexMHllc** [comment]
See related Issue #441

**Comment by b-solution** [comment]
@bluenevus This is working well on our side with latest pull. If error comes again kindly make a demo in video and send us.
https://www.loom.com/share/32085af4027b474083b47359d33f2b54

**Comment by bluenevus** [comment]
@b-solution sent you an email of the recording.  enter name of a node, click enter, doesn't save.  tried to add a node won't do tthat.  Then tried to add a node at the base node then you can see in the video it added a 2nd one and if you type on one, its duplicated on the other and still no save
