### ISSUE TITLE
rather than show a save button, we need to show a delete date with a hover over tool tip that says delete date

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#594]
based on how the system is configured and whether its been saved private or public with a time period, it should show the date it will be deleted here 
![image](https://user-images.githubusercontent.com/3675043/173115840-61d8d492-e50e-49fc-8a6f-68e106fccc5b.png)
 with tool tip that says delete date

This way the user always knows when the document will automatically delete.

by default, if nothing was done on the document its immediately because I'm not saving blank documents

if they did something but didn't save private or public, there is a setting for that in settings.yml
if they save private or public, there is a maximum number of days of inactivity when it will delete

this way if the timer resets because its active, they can see when it will delete leave it be or change the time period by clicking the date if that make sense

**Comment by b-solution** [comment]
@bluenevus I've added tooltip in save button.

**Comment by LAlexMHllc** [comment]
Since file settings.yml has DELETE_AFTER: '6', the tooltip default date when a document has not been saved should be 
today + 6.
Tooltip should also include text "Expires".

Screenshot Example

![default_Save_tooltip_text](https://user-images.githubusercontent.com/11938477/176935385-fa92da6a-eb48-475d-80ab-5e9c42365757.png)

**Comment by b-solution** [comment]
@bluenevus Can you please test it again and let me know if it's not fixed.

**Comment by bluenevus** [comment]
its not fixed
![image](https://user-images.githubusercontent.com/3675043/177357033-ff0029b5-08d6-4ad8-b9b2-07e5893de2ed.png)

1. because I never clicked save and settings yml was setup for 6 days if I didn't save the document, the date should have been 11 Jul because its date +6 which is the date set in the YML if I don't click save.  Remember by default if a user doesn't click save it will only retain it for however many days this was set in the yml  "DELETE_AFTER: .  In my case I put 6 days in the yml which its not using as seen in the image

2.  If I had clicked save then the date would be correct because its date +30 which is in yml for the default.  However, If I changed that to 60 days then its date +60 or what ever the date

**Comment by bluenevus** [comment]
same issue.  see here.  
![image](https://user-images.githubusercontent.com/3675043/177577463-7c9591ed-752b-4337-91f8-e01ec6b5c192.png)

**Comment by bluenevus** [comment]
I clicked save, and it caluclated the tool tip correctly because its 90 days 
![image](https://user-images.githubusercontent.com/3675043/177580173-901dc73a-8170-44ea-ab13-e40829e20a95.png)


but when I click the save button, its 5 days again vs the 90 days I typed previously

![image](https://user-images.githubusercontent.com/3675043/177580289-e2102cb2-a40e-4617-a7e7-4a8ac0be8dad.png)

**Comment by bluenevus** [comment]
This is a mess and we have been going round in circles.  Just undo everything please and have it the way it was before we did the tooltip.  I will ask another developer to do this requirement because its simply getting worse and multiple things are breaking.

**Comment by b-solution** [comment]
@bluenevus I've fixed this issue, can you please test it again and let me know and it's not working for you.

**Comment by LAlexMHllc** [comment]
@b-solution This still does not function correctly at all.
NOTE: Also see related Issue #1032

**Comment by LAlexMHllc** [comment]
Closing, fixed
