### ISSUE TITLE
Spreadsheet: Cell attributes should be in sync for real time collaboration

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#819]
Screenshot Example

![spreadsheet_cell_attributes_should_be_in_sync_for_real_time](https://user-images.githubusercontent.com/11938477/184953638-ec9f7624-7f9f-47bc-b47d-b1cb884781c6.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Still not always in sync

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue. Kindly test it again.

**Comment by LAlexMHllc** [comment]
Still does not consistently update.

Screenshot Example

![spreadsheet_should_consistently_update_to_be_in_sync](https://user-images.githubusercontent.com/11938477/209711658-ef887987-23aa-4cca-8ad0-74b8ecb27dc4.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
