### ISSUE TITLE
Calendar should automatically update without reload browser (create, edit, delete)

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#842]
User input two New Events on separate dates, and neither displayed on the Calendar of the creator, until reload browser.
The events display on the shared screen, because the events existed before the user opened the URL.

Screenshot Example before reload clicked on map creator, and shared URL

![calendar_new_events_should_display_on_calendar_without_reload_browser](https://user-images.githubusercontent.com/11938477/187699553-28f8f027-19c5-4c26-882e-be78ed2b90ba.png)

Screenshot Example after reload clicked on map creator

![calendar_new_events_should_display_on_calendar_without_reload_browser_2](https://user-images.githubusercontent.com/11938477/187699683-1907a0d1-3b32-4979-8c4f-5977ad978b3e.png)

The Calendar should automatically update after successful create, update, and delete without user having to reload browser.

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know if it's not working for you.

**Comment by LAlexMHllc** [comment]
Still needs to be fixed

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
@b-solution  Still not working on production. Please see Sept 9 emails regarding this issue.

**Comment by b-solution** [comment]
@LAlexMHllc we need access to production server or staging.

**Comment by bluenevus** [comment]
it works
