### ISSUE TITLE
Calendar: Exported file missing Month/Year for all views. Sometimes All Day Event missing for Week/Day views, dependent upon Zoom when file downloaded.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#849]
Downloaded files (PDF and PNG) missing info.
Screenshot Example of Export modal

![calendar_export_pdf_image](https://user-images.githubusercontent.com/11938477/187748711-6a0dc735-35f2-49c0-83b6-3749b37410e9.png)

Screenshot Example of Event on Month View

![calendar_month_view](https://user-images.githubusercontent.com/11938477/187747980-c06178a7-3003-46bb-8873-91ae42125b35.png)

Screenshot Example of downloaded file missing Month/Year
NOTE: Month/Year missing on download for Month/Week/Day views

![calendar_month_view_download_missing_month_year](https://user-images.githubusercontent.com/11938477/187748342-0733e9d0-5917-472d-844b-7004abc19e2e.png)

_________________________________________________________________________________________________

Screenshot Example of Events on Week view

![calendar_week_view](https://user-images.githubusercontent.com/11938477/187750563-32fdaa04-ade2-4c5a-b0e2-026991b78552.png)

Screenshot Example of downloaded file missing All Day Event
**NOTE:** For Week/Day views - Sometimes, depending on the Zoom, the All Day Event will not be included on download.

![calendar_export_missing_month_year_and_week_view_missing_all-day_event](https://user-images.githubusercontent.com/11938477/187751107-971cebf8-a037-4e73-ac18-d29aeb495cfe.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Month/Year now display on download file - DONE

- All Day Event still missing sometimes.

- Would like all Events on that Week and Day to display on the download. Currently, only events listed on the first view hours display on download file, even when that Time Range is in view on the screen prior to Export click.

- The view selected should be displayed on the download, instead of always "Day"
Screenshot Examples

![calendar_download_should_have_view_selected_instead_of_always_Day](https://user-images.githubusercontent.com/11938477/189719779-579b7309-7b2d-46fb-b1ef-780c9b128ed1.png)

![calendar_download_should_have_view_selected_instead_of_always_Day_2](https://user-images.githubusercontent.com/11938477/189720533-ae2293b4-b74e-4f0c-a78e-6adee7e29078.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
Downloads for Month view - DONE

Week View download is still missing All Day Event - STILL NEEDS TO BE FIXED

Screenshot Example of Calendar in browser
![calendar_week_view_with_all_day_event](https://user-images.githubusercontent.com/11938477/190697338-b28ae46a-41f7-4750-b5c4-e634525f9d69.png)

Screenshot Example of download missing all day event
![calendar_week_view_with_all_day_event_download_missing_all_day_events](https://user-images.githubusercontent.com/11938477/190697395-47c9193a-874c-4c25-9bef-6803d258776b.png)

____________________________________________________________

Day View download is still missing All Day Event - STILL NEEDS TO BE FIXED

Screenshot Example of Calendar in browser
![calendar_day_view_with_all_day_event](https://user-images.githubusercontent.com/11938477/190697897-97bc597f-a3ec-41f4-a609-6efb4faa60f6.png)

Screenshot Example of download missing all day event
![calendar_day_view_with_all_day_event_download_missing_all_day_events](https://user-images.githubusercontent.com/11938477/190697942-f0ed68f9-11a2-4a7e-9bb5-6a4c05612775.png)
