### ISSUE TITLE
The Save Document Key modal should consistently display with the correct saved number of days.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#964]
Screenshot Example of 60 days selected, then map was Saved

![save_document_key_modal_should_consistently_display_saved_number_of_days](https://user-images.githubusercontent.com/11938477/192336790-b2290b93-b6f8-48f2-8dc3-2ad4c6823ef4.png)

Sometimes the modal displays with a different number of days selected than what was previously saved.
Screenshot Example with modal opening without the correct number of days selected

![save_document_key_modal_should_consistently_display_saved_number_of_days_2](https://user-images.githubusercontent.com/11938477/192336476-a57b0d05-925a-4ea3-bd7f-82cf7b8cbb56.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this issue, can you please test it again and let me know if it's not working for you.

**Comment by LAlexMHllc** [comment]
@b-solution This still does not function correctly.
NOTE: See related Issue #594 and Issue #1032

**Comment by LAlexMHllc** [comment]
Closing, since will be fixed with Issue #1134
